### ISSUE TITLE
Programming a custom BX board from PCB and components

### ISSUE THREAD

**Issue by Charlotte5822** [mattvenn/understanding-tinyfpga-bootloader#1]
Hi, I’ve designed and assembled a custom version of the BX board for a specific project. 

However, I'm encountering issues when trying to program it. The power LED runs well but the other LED doesn't pulse and my PC can't recognize the port due to malfunction.

I understand that the BX's USB bootloader is unique and doesn't require additional chips. If I’m correct, the first step should be programming the AT25SF081 Flash memory using an external microcontroller, followed by initializing the BX. 

Could you please confirm if this is the correct approach or advise on the proper procedure? 

Thank you!

**Comment by mattvenn** [comment]
Hi, sorry it's been such a long time I have no idea really. I would suggest this is the best place to get help: https://github.com/tinyfpga/TinyFPGA-Bootloader
